### ISSUE TITLE
Floating dialog to add missing related node

### ISSUE THREAD

**Issue by brady77** [CulturePlex/Sylva#25]
While editing data (*Graph name* -> Data -> *Data type name* - > Edit) I sometimes realize that the node which I am editing right now  (the left side of the relationship) does not have the related node in the database, yet (the right side of the relationship) . The only option I have in this situation is to drop all the changes I just made to the left side node (by exiting the dialog), creating the right side node and refill all the fields of the left side node again. 

My question is: Is it possible to add a new related node while editing the current node? Something like a click on a button / link (see picture below), that will pop up a floating dialog for adding new node. This new node will be auto-filled into the non-floating dialog (the first opened) just after saving and closing the floating dialog.

Thanks

![2015-02-26_151117](https://cloud.githubusercontent.com/assets/8817469/6393603/d5e4d9ec-bdcb-11e4-9ea0-79ceaecab10c.png)

**Comment by versae** [comment]
That has been a long time requested feature. Maybe it's about time we implement it. But it'll take time :)

**Comment by brady77** [comment]
I've seen this floating dialog somewhere within SylvaDB a time ago, but I couldn't recall where was it. After few clicks I found it, finally:

In the main menu I go to 'Graph' and click the green button 'Analyze'. While having this 'Analyze' window open, I hover 'Data' entry in the main menu. A list of all node types shows with two more buttons for each row: the 'List' button and the 'New' button (the little black plus sign). After I click this 'New' button, a floating dialog opens. I added a screenshot below to show this.

Hopefully it will make the implementation easier for you to replicate this somehow.

![2015-02-27_081653](https://cloud.githubusercontent.com/assets/8817469/6408662/12242f2e-be59-11e4-9e82-466f7bd3096f.png)

**Comment by versae** [comment]
Yes! That is exactly what we have in mind. We started to introduce modal windows in the Analyze mode. But I hope we extend those modals to other places in SylvaDB, such as the creation of related end nodes.

**Comment by brady77** [comment]
Cool, thanks for accepting this request!

**Comment by versae** [comment]
Ups, referenced wrong issue.

**Comment by gabmunrio** [comment]
Hi guys, in the last commit (develop branch) there's a first approach to get a solution for this feature. We will keep improving it, but it's totally functional right now.

Commit 230489fe62daad2b7c434b938ad0fbdf54de441d closes #25
