### ISSUE TITLE
Combination of 'combo box' with 'floating dialog' not working properly

### ISSUE THREAD

**Issue by brady77** [CulturePlex/Sylva#26]
Hi,

first thanks for implementing the ['combo box'](https://github.com/CulturePlex/Sylva/issues/24) and ['floating dialog'](https://github.com/CulturePlex/Sylva/issues/25) features. If the combo box setting is enabled then the floating dialog does not work properly.

Let's say I have the following schema: (Person)-[WORKS_FOR]->(Organization). First I try to add a new instance of type Person: in the editing dialog I fill in the name property. Then I try to add a new (non-existent) target Organization2 within the WORKS_FOR relationship (see step 1 in the screenshot below). A floating dialog pops up to create a new Organization instance. I fill in the name property with Lucas and then I click the Save button (step 2 in the screenshot). The screen darkens a bit, the floating dialog disappears and that's all - nothing is prefilled in the Person edit dialog.

![2015-03-15_113941](https://cloud.githubusercontent.com/assets/8817469/6655776/2a89fbe2-cb0c-11e4-9c74-8f004d20291f.png)

Because of the darkened screen the underlying Person dialog couldn't be saved. On the other hand the new Organization2 was created successfully (without and relationships attached which is obvious because the new Person wasn't saved at all).

Please verify this behaviour and let me know if I'm doing something wrong. Thank you.

Petr

**Comment by versae** [comment]
Thanks for reporting it, Petr. We haven't yet tested enough the new floating dialog. In this case, I don't even know if floating dialog and combo box is still implemented, but it's on its way.

**Comment by gabmunrio** [comment]
Hi Petr, you were right. The combination of combo box and floating dialog didn't work correctly. Right now is fixed, so it should work in a correct way. If you experiment any trouble, feel free to report it. Thanks!

Commit 27db065 closes #26
