### ISSUE TITLE
Problem with node editing in analytics window

### ISSUE THREAD

**Issue by brady77** [CulturePlex/Sylva#27]
I am trying to edit the node in the 'Analytics' window. First I select the node by clicking on it. A dialog pops up at the right side (right below the 'Save as image' button). If I click the 'Edit node data' link then the screen darkens but nothing else happens (see the screenshot attached).

![2015-03-15_124330](https://cloud.githubusercontent.com/assets/8817469/6655881/92dfea98-cb12-11e4-9296-34fb451a1f1a.png)

A similar behaviour is if I mouse over the 'Data' button while on the 'Analytics' page and then I click on the 'Plus' button: the screen darkens but nothing pops up. On the other hand, if i click the 'List' button instead of the 'Plus' button, an floating dialog pops up. So I cannot say that floating dialogs are not working at all.

If I try the webservice (sylvadb.com) everything works perfectly there (editing nodes, listing nodes etc.).

Thanks for verifying.

Petr

**Comment by versae** [comment]
Thanks for reporting this, Petr. We will take a look to see what's going on. We have been doing changes to the modal windows, so we might have broken something.

**Comment by versae** [comment]
Hi Petr, we have been unable to reproduce the error. Is still happening?

**Comment by brady77** [comment]
Hi Javier,

I'm afraid it is still happening. To make the debugging possible a saved two files for you:

1) The [sourcecode](https://sites.google.com/site/filesbypb/home/modal.htm) of the webpage from Firefox with the problem
2) Webserver [logs](https://sites.google.com/site/filesbypb/home/modal.log)

The problem is same from both Chrome and Firefox. On my computer the SylvaDB is running on a VirtualBox with Ubuntu 14.10 server amd64. I have the most recent version of SylvaDB installed.

Should you need any other output, please let me know.

Thank you.

Petr

**Comment by versae** [comment]
Hi Petr,

Could you please provide us with the versions of Chrome and Firefox you are using? Also, a step by step trace that shows how to reproduce it would help.

Sorry for the inconvenience.

**Comment by versae** [comment]
Closed to inactivity. Feel free to reopen.
