### ISSUE TITLE
Query results export without quotations

### ISSUE THREAD

**Issue by brady77** [CulturePlex/Sylva#28]
Hi,

In my database there are some values that are rather of type text. This text may contain commas, as well. If I try run the query within SylvaDb, the results are displayed correctly on webpage. If I try to export those results to CSV (from the 'Main menu' -> 'Tools' -> 'Export query as CSV"), I get a file where columns are separated by commas, only. While my records contain commas, too - the CSV file cannot be processed correctly. Maybe you can tune your code a little so the records in columns are quoted (by quotation marks)? The result will be something like "1","Hello, Kitty!".

Thank you very much.

Petr

**Comment by versae** [comment]
Thanks Petr. Bug [located](https://github.com/CulturePlex/Sylva/blob/develop/sylva/tools/converters.py#L367). We will fix it.

**Comment by gabmunrio** [comment]
Commit b742bc5 closes #28
